"use client"

import React from "react";
import Col from 'react-bootstrap/Col';
import Row from 'react-bootstrap/Row';
import Form from 'react-bootstrap/Form'
import Image from "next/image";
import { MdInfo } from "react-icons/md";
import QrImage from "../../../assets/images/qr-code.svg";

function SecurityData() {
    return (
        <>
            <div className="tab-details">
                <div className="section-title" style={{ fontWeight: "bold", marginBottom: "24px" }}>
                    Security
                </div>
                <div className="section-title" style={{ fontWeight: "bold", marginBottom: "8px" }}>
                    Two-factor Authentication
                </div>
                <div className="input-info" style={{ marginBottom: "24px" }}>2FA adds an extra layer of security to your account. Once enabled, you'll need to provide your password as well as a code from an authenticator app to log in.</div>
                <div className="note-box mb-3">
                    <div className="note-icon">
                        <MdInfo />
                    </div>
                    <div className="note-text">
                        <p>If you haven't already installed an authenticator app on your mobile device, look for one of these free apps in either Apple's App Store or Google's Play Store: Google Authenticator, Last Pass Authenticator, Microsoft Authenticator.</p>
                    </div>
                </div>
                <Form.Check // prettier-ignore
                    type="switch"
                    id="custom-switch"
                    label="Enable 2FA"
                />
                <div className="authenticator-app">
                    <div className="auth-stap">
                        <h4>1. Install a two factor authentication app</h4>
                        <p>Google Authenticator, Last Pass Authenticator, Microsoft Authenticator.</p>
                    </div>
                    <div className="auth-stap">
                        <h4>2. Scan the QR code</h4>
                        <p>Add  your account details to the app and scan the QR code with your phone's camera.</p>
                    </div>
                    <div className="auth-stap">
                        <div className="qr-code">
                            <p>Scan the QR code:</p>
                            <Image src={QrImage} alt="qr-code" />
                        </div>
                    </div>
                    <div className="auth-stap">
                        <h4>3. Enter the code</h4>
                        <p className="mb-2">6 digit code generated by the app</p>
                        <Col md={6}>
                            <Form.Group className="mb-3" controlId="formGroup2fa">
                                <Form.Label>Select the 'Enable 2FA' button after entering the timed code.</Form.Label>
                                <Form.Control type="text" placeholder="" />
                            </Form.Group>
                        </Col>
                        <button className="btn-save">Activate</button>
                    </div>
                    <div className="auth-stap">
                        <h4>4. Done!</h4>
                        <p>Two-factor authentication is now enabled for your account.</p>
                    </div>
                </div>
                <div className="section-title" style={{ fontWeight: "bold", marginBottom: "24px", marginTop: "24px" }}>
                    Change your Password
                </div>
                <Form>
                    <Row>
                        <Col md={12}>
                            <Form.Group className="mb-3" controlId="formGroupPassword">
                                <Form.Label>Current Password*</Form.Label>
                                <Form.Control type="password" placeholder="Password" />
                            </Form.Group>
                        </Col>
                        <Col md={12}>
                            <Form.Group className="mb-3" controlId="formGroupPassword">
                                <Form.Label>New Password*</Form.Label>
                                <Form.Control type="password" placeholder="Password" />
                            </Form.Group>
                        </Col>
                        <Col md={12}>
                            <Form.Group className="mb-3" controlId="formGroupPassword">
                                <Form.Label>Confirm Password*</Form.Label>
                                <Form.Control type="password" placeholder="Password" />
                                <div className="input-info">Password must be at least 12 characters long. Weak password will be marked as invalid. Password must not be greater than 128 characters long.</div>
                            </Form.Group>
                        </Col>
                    </Row>
                </Form>
                <div className="d-flex justify-content-end gap-3 mt-5">
                    <button className="btn-save">
                        Change Password
                    </button>
                </div>
            </div>
        </>
    );
}

export default SecurityData;